### ISSUE TITLE
Ship v7.0

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2076]
This issue is to track progress on shipping v7.0

**Release Notes**
- Drop support for IE9/IE10 (usage of these versions is tiny and Microsoft officially ended support back in 2016. (#2074)
- Move the CSS to a separate repo (#2066)
- Add theme-color meta tag to index.html (#2074)
- Add 'install with yarn' steps to README (#2063)
- Improved Webmanifest (#2060)
- Upgrade Normalize to 8.0.1 (#2104)
- Remove instances of `shrink-to-fit=no` (#2103) 
- Removes "display": "standalone" from manifest (#2096)
- Big Docs update - Fixed links, removed IE9/IE10 specific info, made touch icons section more concise, add details on security.txt and more tidying up (#2074, #2065, #2062)

**Todo List**

- [x] Merge #2066 (main.css integration)
- [x] Review and Merge #2074 (docs update)
- [x] Change hosting for `html5boilerplate.com` to use GitHub Pages
- [x] Remove `CSS.md` docs from repo and direct users to the new main.css repo from `TOC.md`
- [x] Merge `CHANGELOG.md` PR (#2107)
- [x] Publish v7.0 on GitHub
- [x] Publish v7.0 to npm
- [x] Add 'introduction to v7' to html5boilerplate.com
- [x] [Write up the release](https://htmlcssjavascript.com/web/html5-boilerplate-v7-released/)
- [x] Tweet that new release is available

**Comment by roblarsen** [comment]
#2079

**Comment by roblarsen** [comment]
I'm good with merging #2074. I will let it sit until tonight Boston time and then merge it. 

Following that I'll queue up the files for release.

**Comment by roblarsen** [comment]
It looks like we're ready to go. I'll write up something for the new version and push some buttons to release everything as soon as that's queued up.

**Comment by LeoColomb** [comment]
@roblarsen May I release a new version for htaccess from server-configs-apache to include latest changes in v7 or already too late?

**Comment by roblarsen** [comment]
@LeoColomb Not at all. that would be great!

**Comment by miklb** [comment]
Thought this question was more appropriate here than a.new issue, but I'm seeing v6 in main.css still. https://github.com/h5bp/html5-boilerplate/blob/master/dist/css/main.css#L1

Does that need updating in the main repo and rebuilt, a PR here, or are there other plans? Just wanted to make sure looking at the latest version. 

Thanks for keeping this project up, it's always been a great resource 👍

**Comment by roblarsen** [comment]
Thanks for the heads up. I'll take a look at the build and test suite.

**Comment by roblarsen** [comment]
It looks like it was a glitch somewhere in the publishing process. I'm pushing the correct main.css version now.

**Comment by roblarsen** [comment]
I will tweet shortly.

**Comment by roblarsen** [comment]
Tweeted

https://twitter.com/h5bp/status/1095361068732428294

**Comment by roblarsen** [comment]
🚀 🏆 🍾
