### ISSUE TITLE
Ship v7.1.0

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2117]
This issue is to track progress on shipping v7.1.0

**Release Notes**

- Update Modernizr to 3.7.1 (#2121)
- Update Analytics docs and snippet (#2118)
- Minor docs updates (#2115 )
- Minor devdeps updates (#2114)
- More succinct way of writing the IE conditional statement (#2113)

**Todo List**

- [x] Update `CHANGELOG.md`
- [x] Publish v7.1.0 on GitHub (@roblarsen )
- [x] Publish v7.1.0 on NPM (@roblarsen )
- [x] Add additional info to html5boilerplate.com re: this release ?
- [x] Tweet that new release is available (@roblarsen )

**Comment by roblarsen** [comment]
[I'll probably do this tomorrow, but if you're bored Modernizr just released 3.7.1](https://github.com/Modernizr/Modernizr/releases/tag/v3.7.1)

**Comment by roblarsen** [comment]
And then we're good? Just a changelog update, update the package.json and then release? I may have time for that tomorrow too.

**Comment by coliff** [comment]
Yep, if you could take care of that Modernizr update that’d be good. I’m away on a mini vacation without access to computer.

**Comment by coliff** [comment]
very nearly there with this release.. I just have one quick last PR to make re: jQuery CDN that I'd noticed

**Comment by roblarsen** [comment]
🚢 
🚀 
👍

**Comment by coliff** [comment]
Can we add the changelog to the 'release notes' section here https://github.com/h5bp/html5-boilerplate/releases/tag/v7.1.0 ?

**Comment by roblarsen** [comment]
I will tweet at some point today/tomorrow

**Comment by roblarsen** [comment]
Tweettastic.
