### ISSUE TITLE
Ship v7.2.0

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2133]
This issue is to track progress on shipping v7.2.0. It'll be good to get this release out since the current version of H5BP (v7.1.0)  includes jQuery 3.3.1 which has a security vulnerability (https://snyk.io/vuln/npm:jquery). 

**Release Notes**

- Remove `defer` from Google Analytics snippet (#2132)
- Update to jQuery 3.4.1 (#2126)
- Docs updates (#2122, #2125  )
- Update Apache Server Configs to 3.2.1  (#2128)
- Update main.css ?

**Todo List**

- [x] Update main.css  (@roblarsen )
- [x] Review outstanding PRs
- [x] Update `CHANGELOG.md` (@coliff )
- [x] Publish v7.2.0 on GitHub (@roblarsen )
- [x] Publish v7.2.0 on NPM (@roblarsen )
- [x] Add additional info to html5boilerplate.com re: this release ?
- [x] Tweet that new release is available (@roblarsen )

**Comment by roblarsen** [comment]
I'm going to release main.css 2.0.0 and include that here as well. So let me do that, then update the various dependencies across projects and then do this release.

**Comment by coliff** [comment]
great!

**Comment by roblarsen** [comment]
@coliff Want to give this repo a once-over for the release? I think we're good.

**Comment by coliff** [comment]
sure thing... doing a quick review now.

**Comment by roblarsen** [comment]
👀

**Comment by coliff** [comment]
all good from my side, other than we could update the CHANGELOG to add PRs 2134, 2137 and 2138 to the Docs update section...

**Comment by roblarsen** [comment]
Cool. I will publish later this afternoon and then work on the site. Meet you over there 👉

**Comment by roblarsen** [comment]
Released! Documented!
