### ISSUE TITLE
Ship v7.3.0

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2154]
This issue is to track progress on shipping v7.3.0. It'll be great to get this release out with the gulp 4 migration complete.

**Release Notes**

- Upgrade to gulp 4 and update others dev dependencies (#2151)
- Remove .jscsrc config and remove gulp-jscs from package.json (#2153)
- Removed package-lock.json from .gitignore  (#2145)
- bump lowest supported version of node to 8.x (#2142)
- HTTPS link to https://ogp.me/ (#2155)
- Remove redundant rules from .editorconfig (#2157)

**Todo List**

- [x] Review / merge outstanding PR (@roblarsen )
- [x] Update `CHANGELOG.md` (@coliff )
- [x] Publish v7.3.0 on GitHub (@roblarsen )
- [x] Publish v7.3.0 on NPM (@roblarsen )
- [x] Update html5boilerplate.com
- [x] Tweet that new release is available (@roblarsen )

**Comment by roblarsen** [comment]
Oh, i just got access to GitHub actions. I'll try to wire up publishing to npm using the npm actions. That'll give me something extra interesting to write about.

**Comment by roblarsen** [comment]
UPDATE: I'm back from a couple of busy weeks and mini-vacation, so I'm ready to get this release out the door.

**Comment by roblarsen** [comment]
My next three weeks were also busy! I'm back. @coliff I reviewed/merged all the PRs.

**Comment by coliff** [comment]
cool. I'll open a 'Ship 7.3.0' PR with updated `package.json` with version number update and updated `CHANGELOG.md`

**Comment by roblarsen** [comment]
Branching: [release/ship\-v7\.3\.0](https://github.com/h5bp/html5-boilerplate/tree/release/ship-v7.3.0)

**Comment by coliff** [comment]
cool. I'm just making a few small updates to the `CHANGELOG` in that branch and updating version number in `package.json`

**Comment by coliff** [comment]
Minor thing, but in the CHANGELOG you've linked to the commit for 'enabled package-lock.json' - do you think linking to the PR (https://github.com/h5bp/html5-boilerplate/pull/2145) for it may be better in case anyone wants to read the reasoning behind it?

**Comment by coliff** [comment]
Just pushed a commit to that branch with these changes:

- Minor devdeps update for glob and mocha
- Update `CHANGELOG.md` with additional changes and formatting fix (remove leading spaces and extraneous line break)
- Bump version number in `package.json`

**Comment by roblarsen** [comment]
I just noticed an edit to the wiki, _which made me notice that we still have a wiki_. I'm going to move whatever is useful in there to the project itself and turn off the wiki.

**Comment by coliff** [comment]
@roblarsen - the NPM release tag was v7.30 and should have been v7.3.0.
https://github.com/h5bp/html5-boilerplate/releases
Can you fix that?

**Comment by coliff** [comment]
I think we can just edit it here: https://github.com/h5bp/html5-boilerplate/releases/edit/v7.30

**Comment by roblarsen** [comment]
👍

**Comment by roblarsen** [comment]
I haven't tweeted. I'm writing up the blog post now

**Comment by roblarsen** [comment]
Tweeted. Blog posted.
